name: Deploy PRODUCTION Enviroment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy application in Dev Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRD_HOST }}
        username: ${{ secrets.PRD_USERNAME }}
        password: ${{ secrets.PRD_PASSWORD }}
        port: ${{ secrets.PRD_PORT }}
        script:
          /var/www/./deploy.sh ${{ secrets.PRD_SERVERFOLDER }}
